
import { parseStringPromise } from 'xml2js';
import { v4 as uuidv4 } from 'uuid';
import { healXmlContent } from '@/lib/xmlParser';
import type { RMCOARecord, RMTestParameter } from '@/types/rmcoa';

export async function parseRmCoaXml(xmlContent: string, fileName: string): Promise<RMCOARecord | null> {
    // 1. Heal the XML content (fix missing closing tags)
    const healedXml = healXmlContent(xmlContent);

    try {
        // 2. Parse XML
        // explicitArray: false makes it easier to access simple fields, but we need to handle arrays manually
        const result = await parseStringPromise(healedXml, { explicitArray: false });

        if (!result || !result.MATANLCERT) {
             // Try check if it is wrapped differently or throw error
             if (result.matanlcert) {
                 result.MATANLCERT = result.matanlcert;
             } else {
                 throw new Error("Invalid XML Structure: Missing MATANLCERT");
             }
        }

        // Access G_1 data
        // Sometimes it might be an array if multiple G_1 exist, but usually 1 per Cert
        const listG1 = result.MATANLCERT.LIST_G_1 || result.MATANLCERT.list_g_1;
        const g1Raw = listG1?.G_1 || listG1?.g_1;
        
        // Handle array or single object
        const g1 = Array.isArray(g1Raw) ? g1Raw[0] : g1Raw;

        if (!g1) throw new Error("Missing G_1 data");

        // Helper to safely get string
        const getStr = (val: any) => (val && typeof val !== 'object') ? String(val).trim() : '';

        // 3. Extract key fields
        const record: RMCOARecord = {
             // _id will be generated by MongoDB or left undefined here
             arNo: getStr(g1.ARNO || g1.arno),
             materialCode: getStr(g1.MATCODE1 || g1.matcode1), // MATCODE1 seems to be the one (e.g. 1BORI01 in file 3)
             materialName: getStr(g1.MATNAME1 || g1.matname1 || g1.MATDETAIL || g1.matdetail),
             
             batchNumber: getStr(g1.RBATCH || g1.rbatch),
             
             testDate: getStr(g1.ANLDT || g1.anldt),
             testNumber: getStr(g1.MATTRNNO || g1.mattrnno),
             status: getStr(g1.STATUS || g1.status),
             
             manufacturer: getStr(g1.MAKENM || g1.makenm || g1.MAKE || g1.make),
             supplier: getStr(g1.SUPPLIER || g1.supplier),
             quantity: getStr(g1.RECEIVEDQTY || g1.receivedqty),
             uom: getStr(g1.CUOM1 || g1.cuom1),
             mfgDate: getStr(g1.MFGDT || g1.mfgdt),
             expDate: getStr(g1.EXPDT || g1.expdt),
             
             testParameters: [],
             
             sourceFile: fileName,
             parsingStatus: 'success',
             parsingWarnings: []
        };
        
        // 4. Extract test results
        // Structure: LIST_G_SERIAL1 -> G_SERIAL1 -> LIST_G_2 -> G_2
        const listGSerial1 = g1.LIST_G_SERIAL1 || g1.list_g_serial1;
        const gSerial1Raw = listGSerial1?.G_SERIAL1 || listGSerial1?.g_serial1;
        
        let serialGroups: any[] = [];
        if (gSerial1Raw) {
            if (Array.isArray(gSerial1Raw)) {
                serialGroups = gSerial1Raw;
            } else {
                serialGroups = [gSerial1Raw];
            }
        }

        for (const group of serialGroups) {
            const listG2 = group.LIST_G_2 || group.list_g_2;
            const g2Raw = listG2?.G_2 || listG2?.g_2;

            if (g2Raw) {
                let tests: any[] = [];
                 if (Array.isArray(g2Raw)) {
                    tests = g2Raw;
                } else {
                    tests = [g2Raw];
                }

                for (const test of tests) {
                    const testName = getStr(test.PROTEST || test.protest);
                    const resultVal = getStr(test.RESULT || test.result);
                    const limits = getStr(test.LIMITS || test.limits);
                    
                    if (testName) {
                        record.testParameters.push({
                            name: testName,
                            result: resultVal,
                            limits: limits,
                            complies: true // Default to true, logic can be enhanced
                        });
                    }
                }
            }
        }
        
        return record;
    } catch (e) {
        console.error(`Error parsing RM COA XML (${fileName}):`, e);
        return {
            arNo: 'UNKNOWN',
            materialCode: 'UNKNOWN',
            materialName: 'UNKNOWN',
            sourceFile: fileName,
            testParameters: [],
            status: 'ERROR',
            parsingStatus: 'failed',
            parsingWarnings: [e instanceof Error ? e.message : 'Unknown parsing error']
        };
    }
}
